/**
 * dbt Manifest Parser
 *
 * Reads a dbt project's manifest.json (generated by `dbt parse` or `dbt run`)
 * and populates the nodes + edges tables for a workspace.
 *
 * Supported manifest schema versions: v9, v10, v11 (dbt 1.5+)
 */

import fs from 'fs/promises';
import path from 'path';
import { pool } from '../db/pool.js';

// ── Types mirroring dbt manifest.json ────────────────────────────────────────

interface DbtNode {
  unique_id: string;
  name: string;
  resource_type: 'model' | 'source' | 'seed' | 'snapshot' | 'test' | 'exposure' | 'metric';
  description: string;
  original_file_path: string;
  compiled_code?: string;
  raw_code?: string;
  config?: Record<string, unknown>;
  columns?: Record<string, { name: string; description: string; data_type?: string }>;
  depends_on?: { nodes: string[] };
  tags?: string[];
  meta?: Record<string, unknown>;
  fqn?: string[];
  database?: string;
  schema?: string;
  refs?: string[][];
  sources?: string[][];
}

interface DbtSource {
  unique_id: string;
  name: string;
  source_name: string;
  description: string;
  original_file_path: string;
  columns?: Record<string, { name: string; description: string; data_type?: string }>;
  tags?: string[];
  meta?: Record<string, unknown>;
  database?: string;
  schema?: string;
}

interface DbtManifest {
  metadata: { dbt_schema_version: string; dbt_version: string; generated_at: string };
  nodes: Record<string, DbtNode>;
  sources: Record<string, DbtSource>;
  exposures?: Record<string, unknown>;
  metrics?: Record<string, unknown>;
  parent_map?: Record<string, string[]>;
  child_map?: Record<string, string[]>;
}

// ── Parsed result returned to callers ────────────────────────────────────────

export interface ParsedProject {
  projectName: string;
  dbtVersion: string;
  generatedAt: string;
  nodeCount: number;
  edgeCount: number;
  models: ParsedModel[];
  sources: ParsedSource[];
}

export interface ParsedModel {
  uniqueId: string;
  name: string;
  resourceType: string;
  description: string;
  filePath: string;
  sql: string;
  config: Record<string, unknown>;
  columns: Array<{ name: string; description: string; dataType?: string }>;
  tags: string[];
  meta: Record<string, unknown>;
  dependsOn: string[];   // unique_ids of upstream nodes
}

export interface ParsedSource {
  uniqueId: string;
  name: string;
  sourceName: string;
  description: string;
  filePath: string;
  columns: Array<{ name: string; description: string; dataType?: string }>;
  tags: string[];
  meta: Record<string, unknown>;
}

// ── Main entry point ──────────────────────────────────────────────────────────

/**
 * Parse a dbt project and persist nodes + edges into PostgreSQL.
 *
 * @param projectPath  Absolute path to the dbt project root.
 * @param workspaceId  Workspace that owns this parse result.
 * @param environmentId Optional environment to associate nodes with.
 * @returns Summary of what was parsed and stored.
 */
/**
 * Resolve and validate a project path against the allowed base directory.
 * Throws if the resolved path escapes the allowed directory.
 */
export function resolveProjectPath(rawPath: string): string {
  // Allowed base: DBT_PROJECTS_DIR env var, or /dbt_projects, or cwd in dev
  const allowedBase = path.resolve(
    process.env.DBT_PROJECTS_DIR ?? (process.env.NODE_ENV === 'production' ? '/dbt_projects' : process.cwd()),
  );
  const resolved = path.resolve(rawPath);
  if (!resolved.startsWith(allowedBase + path.sep) && resolved !== allowedBase) {
    throw new Error(
      `Project path "${resolved}" is outside the allowed directory "${allowedBase}". ` +
      `Set DBT_PROJECTS_DIR env var to allow a different base.`,
    );
  }
  return resolved;
}

export async function parseDbtProject(
  projectPath: string,
  workspaceId: string,
  environmentId?: string,
): Promise<ParsedProject> {
  const safePath = resolveProjectPath(projectPath);
  const manifestPath = await findManifest(safePath);

  let raw: string;
  try {
    raw = await fs.readFile(manifestPath, 'utf-8');
  } catch (err) {
    throw new Error(`Failed to read manifest at "${manifestPath}": ${String(err)}`);
  }

  let manifest: DbtManifest;
  try {
    manifest = JSON.parse(raw) as DbtManifest;
  } catch {
    throw new Error(
      `manifest.json at "${manifestPath}" is not valid JSON. ` +
      `Re-run "dbt parse" to regenerate it.`,
    );
  }

  if (!manifest?.metadata || !manifest?.nodes) {
    throw new Error(
      `manifest.json at "${manifestPath}" is missing required fields (metadata, nodes). ` +
      `This may be an unsupported dbt version (requires dbt 1.5+ / schema v9+).`,
    );
  }

  const models = extractModels(manifest);
  const sources = extractSources(manifest);

  // Upsert nodes for models + sources, then edges for dependencies
  await persistNodes(models, sources, workspaceId, environmentId);
  const edgeCount = await persistEdges(manifest, workspaceId);

  // Derive project name from the first model's fqn[0] or directory name
  const firstModel = Object.values(manifest.nodes).find(n => n.resource_type === 'model');
  const projectName = firstModel?.fqn?.[0] ?? path.basename(safePath);

  return {
    projectName,
    dbtVersion: manifest.metadata.dbt_version,
    generatedAt: manifest.metadata.generated_at,
    nodeCount: models.length + sources.length,
    edgeCount,
    models,
    sources,
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function findManifest(projectPath: string): Promise<string> {
  const candidates = [
    path.join(projectPath, 'target', 'manifest.json'),
    path.join(projectPath, 'manifest.json'),
  ];
  for (const p of candidates) {
    try {
      await fs.access(p);
      return p;
    } catch {
      // not found at this path — try next
    }
  }
  throw new Error(
    `manifest.json not found in "${projectPath}". ` +
    `Run "dbt parse" or "dbt run" inside your dbt project first.`,
  );
}

function extractModels(manifest: DbtManifest): ParsedModel[] {
  return Object.values(manifest.nodes)
    .filter(n => ['model', 'seed', 'snapshot'].includes(n.resource_type))
    .map(n => ({
      uniqueId: n.unique_id,
      name: n.name,
      resourceType: n.resource_type,
      description: n.description ?? '',
      filePath: n.original_file_path ?? '',
      sql: n.compiled_code ?? n.raw_code ?? '',
      config: n.config ?? {},
      columns: Object.values(n.columns ?? {}).map(c => ({
        name: c.name,
        description: c.description ?? '',
        dataType: c.data_type,
      })),
      tags: n.tags ?? [],
      meta: n.meta ?? {},
      dependsOn: n.depends_on?.nodes ?? [],
    }));
}

function extractSources(manifest: DbtManifest): ParsedSource[] {
  return Object.values(manifest.sources).map(s => ({
    uniqueId: s.unique_id,
    name: s.name,
    sourceName: s.source_name,
    description: s.description ?? '',
    filePath: s.original_file_path ?? '',
    columns: Object.values(s.columns ?? {}).map(c => ({
      name: c.name,
      description: c.description ?? '',
      dataType: c.data_type,
    })),
    tags: s.tags ?? [],
    meta: s.meta ?? {},
  }));
}

async function persistNodes(
  models: ParsedModel[],
  sources: ParsedSource[],
  workspaceId: string,
  environmentId?: string,
): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    for (const m of models) {
      await client.query(
        `INSERT INTO nodes (workspace_id, environment_id, name, type, description, metadata, config)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (workspace_id, name) DO UPDATE SET
           description = EXCLUDED.description,
           metadata    = EXCLUDED.metadata,
           config      = EXCLUDED.config`,
        [
          workspaceId,
          environmentId ?? null,
          m.name,
          m.resourceType,
          m.description,
          JSON.stringify({ uniqueId: m.uniqueId, filePath: m.filePath, sql: m.sql, columns: m.columns, tags: m.tags, meta: m.meta }),
          JSON.stringify(m.config),
        ],
      );
    }

    for (const s of sources) {
      await client.query(
        `INSERT INTO nodes (workspace_id, environment_id, name, type, description, metadata, config)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (workspace_id, name) DO UPDATE SET
           description = EXCLUDED.description,
           metadata    = EXCLUDED.metadata,
           config      = EXCLUDED.config`,
        [
          workspaceId,
          environmentId ?? null,
          `${s.sourceName}.${s.name}`,
          'source',
          s.description,
          JSON.stringify({ uniqueId: s.uniqueId, filePath: s.filePath, columns: s.columns, tags: s.tags, meta: s.meta }),
          '{}',
        ],
      );
    }

    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

async function persistEdges(manifest: DbtManifest, workspaceId: string): Promise<number> {
  // Build a name → DB id map
  const nodeRows = await pool.query<{ id: string; name: string }>(
    `SELECT id, name FROM nodes WHERE workspace_id = $1`,
    [workspaceId],
  );
  const nameToId = new Map(nodeRows.rows.map(r => [r.name, r.id]));

  const allNodes: DbtNode[] = Object.values(manifest.nodes).filter(n =>
    ['model', 'seed', 'snapshot'].includes(n.resource_type),
  );

  const client = await pool.connect();
  let edgeCount = 0;
  try {
    await client.query('BEGIN');
    // Delete stale edges for this workspace before re-inserting
    await client.query(
      `DELETE FROM edges WHERE source_node_id IN (SELECT id FROM nodes WHERE workspace_id = $1)`,
      [workspaceId],
    );

    for (const node of allNodes) {
      const targetId = nameToId.get(node.name);
      if (!targetId) continue;

      for (const depUniqueId of node.depends_on?.nodes ?? []) {
        // Map unique_id back to name  (format: "model.project.name" or "source.project.src.name")
        const depName = uniqueIdToName(depUniqueId, manifest);
        const sourceId = nameToId.get(depName);
        if (!sourceId) continue;

        await client.query(
          `INSERT INTO edges (source_node_id, target_node_id, label, metadata)
           VALUES ($1, $2, $3, $4)
           ON CONFLICT DO NOTHING`,
          [sourceId, targetId, 'ref', '{}'],
        );
        edgeCount++;
      }
    }

    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  return edgeCount;
}

function uniqueIdToName(uniqueId: string, manifest: DbtManifest): string {
  const node = manifest.nodes[uniqueId];
  if (node) return node.name;
  const src = manifest.sources[uniqueId];
  if (src) return `${src.source_name}.${src.name}`;
  // Fallback: last segment of unique_id
  const parts = uniqueId.split('.');
  return parts[parts.length - 1];
}
