"""Export findings to multiple enterprise formats.

Supports:
- JSON (default)
- CSV
- HTML
- SARIF (for GitHub/GitLab code scanning)
- Jira-ready format
- Airflow DAG artifacts
- Power BI dataset schema
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger()


def export_json(report: dict, output_path: str, **kwargs: Any) -> str:
    """Export as JSON."""
    path = Path(output_path) / "datapilot_report.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, default=str)
    return str(path)


def export_csv(report: dict, output_path: str, **kwargs: Any) -> str:
    """Export findings as CSV for spreadsheet tools."""
    path = Path(output_path) / "datapilot_findings.csv"
    findings = report.get("findings", [])

    if not findings:
        return str(path)

    fieldnames = ["type", "model", "severity", "evidence", "cost_usd", "action"]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for finding in findings:
            writer.writerow(finding)

    return str(path)


def export_sarif(report: dict, output_path: str, **kwargs: Any) -> str:
    """Export as SARIF for GitHub/GitLab code scanning integration."""
    path = Path(output_path) / "datapilot_report.sarif"

    results = []
    rules = []
    seen_rules: set[str] = set()

    for finding in report.get("findings", []):
        rule_id = finding.get("type", "unknown")

        if rule_id not in seen_rules:
            seen_rules.add(rule_id)
            severity_map = {
                "critical": "error",
                "high": "warning",
                "medium": "note",
                "low": "note",
            }
            rules.append(
                {
                    "id": rule_id,
                    "shortDescription": {"text": rule_id.replace("_", " ").title()},
                    "defaultConfiguration": {
                        "level": severity_map.get(finding.get("severity", "medium"), "note")
                    },
                }
            )

        results.append(
            {
                "ruleId": rule_id,
                "message": {
                    "text": (
                        f"[{finding.get('model', '?')}] {finding.get('evidence', '')}\n"
                        f"Action: {finding.get('action', '')}"
                    )
                },
                "level": {
                    "critical": "error",
                    "high": "warning",
                    "medium": "note",
                    "low": "note",
                }.get(finding.get("severity", "medium"), "note"),
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": f"models/{finding.get('model', 'unknown')}.sql"
                            }
                        }
                    }
                ],
            }
        )

    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "DataPilot",
                        "version": "2.0.0",
                        "informationUri": "https://github.com/BVB09TS/Data-Pilot",
                        "rules": rules,
                    }
                },
                "results": results,
            }
        ],
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(sarif, f, indent=2)

    return str(path)


def export_jira(report: dict, output_path: str, **kwargs: Any) -> str:
    """Export findings as Jira-importable JSON."""
    path = Path(output_path) / "datapilot_jira_issues.json"

    priority_map = {"critical": "Highest", "high": "High", "medium": "Medium", "low": "Low"}

    issues = []
    for finding in report.get("findings", []):
        issues.append(
            {
                "summary": f"[DataPilot] {finding.get('type', 'issue').replace('_', ' ').title()}: {finding.get('model', '?')}",
                "description": (
                    f"*Evidence:* {finding.get('evidence', 'N/A')}\n\n"
                    f"*Recommended Action:* {finding.get('action', 'N/A')}\n\n"
                    f"*Estimated Cost:* ${finding.get('cost_usd', 0)}/month\n\n"
                    f"_Generated by DataPilot v2.0_"
                ),
                "priority": priority_map.get(finding.get("severity", "medium"), "Medium"),
                "labels": ["datapilot", "data-quality", finding.get("type", "")],
                "issuetype": "Bug" if finding.get("severity") == "critical" else "Task",
            }
        )

    with open(path, "w", encoding="utf-8") as f:
        json.dump({"issues": issues}, f, indent=2)

    return str(path)


def export_powerbi_schema(output_path: str, **kwargs: Any) -> str:
    """Generate Power BI dataset schema for push datasets."""
    path = Path(output_path) / "datapilot_powerbi_schema.json"

    schema = {
        "name": "DataPilotFindings",
        "tables": [
            {
                "name": "DataPilotFindings",
                "columns": [
                    {"name": "model", "dataType": "String"},
                    {"name": "type", "dataType": "String"},
                    {"name": "severity", "dataType": "String"},
                    {"name": "evidence", "dataType": "String"},
                    {"name": "cost_usd", "dataType": "Double"},
                    {"name": "action", "dataType": "String"},
                    {"name": "generated_at", "dataType": "DateTime"},
                ],
            },
            {
                "name": "DataPilotSummary",
                "columns": [
                    {"name": "generated_at", "dataType": "DateTime"},
                    {"name": "total_findings", "dataType": "Int64"},
                    {"name": "critical_count", "dataType": "Int64"},
                    {"name": "high_count", "dataType": "Int64"},
                    {"name": "waste_usd", "dataType": "Double"},
                ],
            },
        ],
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2)

    return str(path)


EXPORTERS = {
    "json": export_json,
    "csv": export_csv,
    "sarif": export_sarif,
    "jira": export_jira,
}


def export_all(report: dict, output_path: str, formats: list[str] | None = None) -> dict[str, str]:
    """Export report in multiple formats."""
    formats = formats or ["json"]
    Path(output_path).mkdir(parents=True, exist_ok=True)

    results = {}
    for fmt in formats:
        exporter = EXPORTERS.get(fmt)
        if exporter:
            try:
                path = exporter(report, output_path)
                results[fmt] = path
                logger.info("exported", format=fmt, path=path)
            except Exception as e:
                logger.error("export_failed", format=fmt, error=str(e))
                results[fmt] = f"ERROR: {e}"
        else:
            results[fmt] = f"Unknown format: {fmt}"

    return results
