"""Apache Airflow integration — generate DAGs and trigger audits."""

from __future__ import annotations

import json
import os
from typing import Any

import structlog

from datapilot.integrations.base import Integration

logger = structlog.get_logger()

AIRFLOW_DAG_TEMPLATE = '''"""Auto-generated DataPilot audit DAG for Airflow.

This DAG runs the DataPilot dbt audit pipeline on a schedule.
Generated by DataPilot v2.0 integration system.
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
from airflow.models import Variable

default_args = {{
    "owner": "datapilot",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": {retries},
    "retry_delay": timedelta(minutes={retry_delay_min}),
}}

with DAG(
    dag_id="{dag_id}",
    default_args=default_args,
    description="DataPilot dbt project audit",
    schedule_interval="{schedule}",
    start_date=datetime({start_year}, 1, 1),
    catchup=False,
    tags=["datapilot", "dbt", "audit", "data-quality"],
) as dag:

    run_audit = BashOperator(
        task_id="run_datapilot_audit",
        bash_command=(
            "datapilot audit "
            "--project {project_path} "
            "--output {output_path} "
            "--config {config_path} "
        ),
    )

    publish_results = PythonOperator(
        task_id="publish_results",
        python_callable=_publish_results,
        op_kwargs={{"output_path": "{output_path}"}},
    )

    notify = PythonOperator(
        task_id="notify_on_critical",
        python_callable=_notify_critical_findings,
        op_kwargs={{"output_path": "{output_path}"}},
    )

    run_audit >> publish_results >> notify


def _publish_results(output_path: str, **kwargs):
    """Push report to XCom for downstream tasks."""
    import json
    report_path = f"{{output_path}}/datapilot_report.json"
    with open(report_path) as f:
        report = json.load(f)
    kwargs["ti"].xcom_push(key="datapilot_report", value=report.get("report", {{}}))


def _notify_critical_findings(output_path: str, **kwargs):
    """Alert on critical findings."""
    report = kwargs["ti"].xcom_pull(task_ids="publish_results", key="datapilot_report")
    if not report:
        return
    critical = [f for f in report.get("findings", []) if f.get("severity") == "critical"]
    if critical:
        print(f"ALERT: {{len(critical)}} critical findings detected!")
        for f in critical:
            print(f"  - [{{f['type']}}] {{f['model']}}: {{f['evidence']}}")
'''


class AirflowIntegration(Integration):
    """Generate Airflow DAGs and integrate with Airflow REST API."""

    def __init__(
        self,
        base_url: str = "",
        dag_folder: str = "",
        project_path: str = ".",
        output_path: str = "./output",
        config_path: str = "./datapilot.yaml",
    ):
        self._base_url = base_url
        self._dag_folder = dag_folder
        self._project_path = project_path
        self._output_path = output_path
        self._config_path = config_path

    @property
    def name(self) -> str:
        return "Apache Airflow"

    @property
    def platform(self) -> str:
        return "airflow"

    def is_configured(self) -> bool:
        return bool(self._dag_folder)

    def health_check(self) -> dict[str, Any]:
        if not self._base_url:
            return {"status": "unconfigured", "message": "No Airflow base URL set"}
        try:
            import httpx

            resp = httpx.get(f"{self._base_url}/api/v1/health", timeout=10)
            return {"status": "healthy" if resp.status_code == 200 else "unhealthy"}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def generate_dag(
        self,
        dag_id: str = "datapilot_dbt_audit",
        schedule: str = "@daily",
        retries: int = 2,
        retry_delay_min: int = 5,
    ) -> str:
        """Generate an Airflow DAG file for scheduled audits."""
        from datetime import datetime

        content = AIRFLOW_DAG_TEMPLATE.format(
            dag_id=dag_id,
            schedule=schedule,
            retries=retries,
            retry_delay_min=retry_delay_min,
            start_year=datetime.now().year,
            project_path=self._project_path,
            output_path=self._output_path,
            config_path=self._config_path,
        )

        if self._dag_folder:
            dag_path = os.path.join(self._dag_folder, f"{dag_id}.py")
            os.makedirs(self._dag_folder, exist_ok=True)
            with open(dag_path, "w") as f:
                f.write(content)
            logger.info("airflow_dag_generated", path=dag_path)

        return content

    def publish_report(self, report: dict, **kwargs: Any) -> dict[str, Any]:
        """Publish report via Airflow's REST API (trigger a DAG run with conf)."""
        if not self._base_url:
            return {"status": "skipped", "reason": "No base URL configured"}

        try:
            import httpx

            resp = httpx.post(
                f"{self._base_url}/api/v1/dags/datapilot_dbt_audit/dagRuns",
                json={
                    "conf": {
                        "total_findings": report.get("total_findings", 0),
                        "critical_count": report.get("by_severity", {}).get("critical", 0),
                        "waste_usd": report.get("total_monthly_waste_usd", 0),
                    }
                },
                timeout=30,
            )
            return {"status": "published", "response_code": resp.status_code}
        except Exception as e:
            return {"status": "error", "error": str(e)}
